<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    /**
     * Retourne la liste des jobs dont la date est supérieure a la date du
     * du jour
     * @return Collection<AppBundle:TJob> Liste des jobs
     */
    public function findActiveJobs() {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM AppBundle:TJob p WHERE p.date > :sysdate ORDER BY p.date ASC')
                    ->setParameter('sysdate', new \DateTime('now'))
                    ->getResult();
    }
}
