<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository as EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllUsersSortByName() {
        return $this->getEntityManager()
                   ->createQuery('SELECT u FROM AppBundle:TUser u SORT BY username ASC')
                   ->getResult();
    }

    public function getUserByLogin($login) {
      return $this->findOneBy(array('username' => $login));
    }
}
